### ISSUE TITLE
Problems whith Banner

### ISSUE THREAD

**Issue by yaelduckwen** [cpearson3/bootsmooth-uikit-theme#1]
First, thanks for this great theme. But I'm having problems with the Banner widget, nothing ever appears to me if I use that place.

**Comment by cpearson3** [comment]
Thanks for checking out the project. The issue has been fixed in ```functions.php``` and the banner widget area is now loaded in the ```index.twig``` template.

**Comment by yaelduckwen** [comment]
Thanks for such a quick response! I'm going to review it and I'll tell you
